name: Portfolio CI/CD

on:
  push:
    branches:
      - main

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Frontend Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/portfolio-frontend:latest ./frontend

      - name: Build Backend Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/portfolio-backend:latest ./backend

      - name: Push Frontend Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/portfolio-frontend:latest

      - name: Push Backend Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/portfolio-backend:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |

            docker pull ${{ secrets.DOCKER_USERNAME }}/portfolio-frontend:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/portfolio-backend:latest

            docker stop frontend || true
            docker rm frontend || true

            docker stop backend || true
            docker rm backend || true

            docker run -d \
              --name frontend \
              -p 80:5173 \
              ${{ secrets.DOCKER_USERNAME }}/portfolio-frontend:latest

            docker run -d \
              --name backend \
              -p 30002:30002 \
              ${{ secrets.DOCKER_USERNAME }}/portfolio-backend:latest